/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package otoder;

import javax.swing.JFrame;

/**
 *
 * @author Cihan
 */
public class DershanePaneli extends javax.swing.JFrame {

    int m_adminId ;
    JFrame m_previousJFrame;
    /**
     * Creates new form DershanePaneli
     */
    public DershanePaneli( int admin_id, JFrame previousView ) {
        m_adminId = admin_id;
        m_previousJFrame = previousView;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOgrenciMenusu = new javax.swing.JButton();
        buttonOgretmenMenusu = new javax.swing.JButton();
        buttonSinavlar = new javax.swing.JButton();
        buttonSiniflar = new javax.swing.JButton();
        button = new javax.swing.JButton();
        buttonDersProgrami = new javax.swing.JButton();
        buttonRaporlar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonOgrenciMenusu.setText("Öğrenci Menüsü");
        buttonOgrenciMenusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOgrenciMenusuMouseClicked(evt);
            }
        });

        buttonOgretmenMenusu.setText("Öğretmen Menüsü");
        buttonOgretmenMenusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOgretmenMenusuMouseClicked(evt);
            }
        });

        buttonSinavlar.setText("Sınavlar");
        buttonSinavlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSinavlarMouseClicked(evt);
            }
        });

        buttonSiniflar.setText("Sınıflar");
        buttonSiniflar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSiniflarMouseClicked(evt);
            }
        });

        button.setText("Sınıfları Belirle");
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });

        buttonDersProgrami.setText("Ders Programı Olustur");
        buttonDersProgrami.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDersProgramiMouseClicked(evt);
            }
        });

        buttonRaporlar.setText("Raporlar");
        buttonRaporlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRaporlarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonOgretmenMenusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOgrenciMenusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSinavlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSiniflar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDersProgrami, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(buttonRaporlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOgrenciMenusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOgretmenMenusu)
                .addGap(48, 48, 48)
                .addComponent(buttonSinavlar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSiniflar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDersProgrami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRaporlar)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOgrenciMenusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOgrenciMenusuMouseClicked
        this.setVisible(false);
        OgrenciPaneli ogrc_pan = new OgrenciPaneli( this );
        ogrc_pan.setVisible(true);
    }//GEN-LAST:event_buttonOgrenciMenusuMouseClicked

    private void buttonOgretmenMenusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOgretmenMenusuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        OgretmenPaneli ogrt_pan = new OgretmenPaneli( this );
        ogrt_pan.setVisible(true);
    }//GEN-LAST:event_buttonOgretmenMenusuMouseClicked

    private void buttonSinavlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSinavlarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSinavlarMouseClicked

    private void buttonSiniflarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSiniflarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSiniflarMouseClicked

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMouseClicked

    private void buttonDersProgramiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDersProgramiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDersProgramiMouseClicked

    private void buttonRaporlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRaporlarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRaporlarMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DershanePaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DershanePaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DershanePaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DershanePaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new DershanePaneli().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JButton buttonDersProgrami;
    private javax.swing.JButton buttonOgrenciMenusu;
    private javax.swing.JButton buttonOgretmenMenusu;
    private javax.swing.JButton buttonRaporlar;
    private javax.swing.JButton buttonSinavlar;
    private javax.swing.JButton buttonSiniflar;
    // End of variables declaration//GEN-END:variables
}