/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package otoder;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import utils.DBHelper;

/**
 *
 * @author Cihan
 */
public class OgrenciBilgiPaneli extends javax.swing.JFrame {

    JFrame previousJFrame;
    /**
     * Creates new form OgrenciBilgiPaneli
     */
    public OgrenciBilgiPaneli( JFrame jframe ) {
        previousJFrame = jframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIsim = new javax.swing.JTextField();
        jTextFieldSoyisim = new javax.swing.JTextField();
        jTextFieldSeviye = new javax.swing.JTextField();
        jTextFieldSinif = new javax.swing.JTextField();
        jButtonIptal = new javax.swing.JButton();
        jButtonTamam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldSinif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSinifActionPerformed(evt);
            }
        });

        jButtonIptal.setText("İptal");
        jButtonIptal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIptalMouseClicked(evt);
            }
        });

        jButtonTamam.setText("Tamam");
        jButtonTamam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTamamMouseClicked(evt);
            }
        });

        jLabel1.setText("İsim        :");

        jLabel2.setText("Sınıf        :");

        jLabel3.setText("Seviye    :");

        jLabel4.setText("Soyisim   :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSoyisim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jTextFieldIsim, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldSeviye)
                    .addComponent(jTextFieldSinif))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTamam)
                    .addComponent(jButtonIptal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonTamam)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIsim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSoyisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSeviye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonIptal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSinif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIptalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIptalMouseClicked
        previousJFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIptalMouseClicked

    private void jButtonTamamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTamamMouseClicked
        
        ogrenciKaydet();
        previousJFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonTamamMouseClicked

    private void jTextFieldSinifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSinifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSinifActionPerformed

    private boolean ogrenciKaydet(){

        ArrayList<String> kolonIsim = new ArrayList<>();
        ArrayList<String> bilgiler  = new ArrayList<>();
        
        kolonIsim.add( "isim" );
        kolonIsim.add("soyisim");
        kolonIsim.add("seviye");
        kolonIsim.add("sinif");
        kolonIsim.add("no");
        
        bilgiler.add( jTextFieldIsim.getText().toString() );
        bilgiler.add( jTextFieldSoyisim.getText().toString() );
        bilgiler.add( jTextFieldSeviye.getText().toString() );
        bilgiler.add( jTextFieldSinif.getText().toString() );

        DBHelper dbHelper = new DBHelper("otoder");
        
        ResultSet rs = dbHelper.recordSelect("ogrenci", "*", "", "");
        int rowcount = 0;
        Integer newStudentNo = 0 ;
        try {
            if (rs.last()) {
              rowcount = rs.getRow();
              newStudentNo = Integer.parseInt( rs.getString("no").toString() );
              rs.beforeFirst(); // not rs.first() because the rs.next() below will move on, missing the first element
            }
        } catch (SQLException ex) {
            Logger.getLogger(OgrenciBilgiPaneli.class.getName()).log(Level.SEVERE, null, ex);
        }
        newStudentNo++;
        bilgiler.add( newStudentNo.toString() );
        dbHelper.recordInsert("ogrenci", kolonIsim, bilgiler);
        
        
        
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIptal;
    private javax.swing.JButton jButtonTamam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldIsim;
    private javax.swing.JTextField jTextFieldSeviye;
    private javax.swing.JTextField jTextFieldSinif;
    private javax.swing.JTextField jTextFieldSoyisim;
    // End of variables declaration//GEN-END:variables
}
