/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package otoder;

import javax.swing.JFrame;
import utils.DBHelper;

/**
 *
 * @author Cihan
 */
public class OgrenciPaneli extends javax.swing.JFrame {

    JFrame m_previous;
    /**
     * Creates new form OgrenciPaneli
     */
    public OgrenciPaneli( JFrame previous ) {
        m_previous = previous;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonOgrenciKayit = new javax.swing.JButton();
        buttonOgrenciDuzenle = new javax.swing.JButton();
        buttonSinavBilgileri = new javax.swing.JButton();
        buttonOdemeBilgileri = new javax.swing.JButton();
        jButtonCikis = new javax.swing.JButton();
        jButtonOgrenciSil = new javax.swing.JButton();
        jTextFieldOgrenciNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonOgrenciKayit.setText("Öğrenci Kayıt");
        buttonOgrenciKayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOgrenciKayitMouseClicked(evt);
            }
        });

        buttonOgrenciDuzenle.setText("Öğrenci Düzenle");
        buttonOgrenciDuzenle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOgrenciDuzenleMouseClicked(evt);
            }
        });

        buttonSinavBilgileri.setText("Sınav Bilgilerini Görüntüle");
        buttonSinavBilgileri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSinavBilgileriMouseClicked(evt);
            }
        });

        buttonOdemeBilgileri.setText("Ödeme Bilgilerini Görüntüle");
        buttonOdemeBilgileri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOdemeBilgileriMouseClicked(evt);
            }
        });

        jButtonCikis.setText("Çıkış");
        jButtonCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCikisMouseClicked(evt);
            }
        });

        jButtonOgrenciSil.setText("Öğrenci Sil");
        jButtonOgrenciSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOgrenciSilMouseClicked(evt);
            }
        });

        jLabel1.setText("Öğrenci Numarası");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSinavBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOgrenciDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOgrenciKayit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOdemeBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldOgrenciNo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addComponent(jButtonOgrenciSil, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOgrenciKayit)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOgrenciDuzenle)
                    .addComponent(jButtonOgrenciSil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOgrenciNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSinavBilgileri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOdemeBilgileri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCikis)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOgrenciKayitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOgrenciKayitMouseClicked
        this.setVisible(false);
        OgrenciBilgiPaneli ogrBilgiPan = new OgrenciBilgiPaneli( this );
        ogrBilgiPan.setVisible(true);
    }//GEN-LAST:event_buttonOgrenciKayitMouseClicked

    private void buttonOgrenciDuzenleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOgrenciDuzenleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOgrenciDuzenleMouseClicked

    private void buttonSinavBilgileriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSinavBilgileriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSinavBilgileriMouseClicked

    private void buttonOdemeBilgileriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOdemeBilgileriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOdemeBilgileriMouseClicked

    private void jButtonCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCikisMouseClicked
        // TODO add your handling code here:
        m_previous.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCikisMouseClicked

    private void jButtonOgrenciSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOgrenciSilMouseClicked
        ogrenciSil( );
    }//GEN-LAST:event_jButtonOgrenciSilMouseClicked

    public boolean ogrenciSil(){
        
        String no = jTextFieldOgrenciNo.getText().toString();
        DBHelper dbHelper = new DBHelper("otoder");
        dbHelper.recordDelete("ogrenci", "no="+no);
        
        
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOdemeBilgileri;
    private javax.swing.JButton buttonOgrenciDuzenle;
    private javax.swing.JButton buttonOgrenciKayit;
    private javax.swing.JButton buttonSinavBilgileri;
    private javax.swing.JButton jButtonCikis;
    private javax.swing.JButton jButtonOgrenciSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldOgrenciNo;
    // End of variables declaration//GEN-END:variables
}
