/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OgretmenBilgiPaneli.java
 *
 * Created on 10.May.2012, 02:04:31
 */
package otoder;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import utils.BilgilendirmePaneli;
import utils.DBHelper;

/**
 *
 * @author halil
 */
public class OgretmenBilgiPaneli extends javax.swing.JFrame {
    
    JFrame previousJFrame;

    /** Creates new form OgretmenBilgiPaneli */
    public OgretmenBilgiPaneli( JFrame previous) {
        previousJFrame = previous;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adLbl = new javax.swing.JLabel();
        soyadLbl = new javax.swing.JLabel();
        bransLbl = new javax.swing.JLabel();
        isimLbl3 = new javax.swing.JLabel();
        adTxtFld = new javax.swing.JTextField();
        soyadTxtFld = new javax.swing.JTextField();
        bransTxtFld = new javax.swing.JTextField();
        dbKaydetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonTamam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adLbl.setText("AD :");

        soyadLbl.setText("SOYAD  : ");

        bransLbl.setText("BRANŞ : ");

        adTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adTxtFldActionPerformed(evt);
            }
        });

        dbKaydetBtn.setText("Kaydet");
        dbKaydetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbKaydetBtnMouseClicked(evt);
            }
        });

        jLabel1.setText("isim ");

        jLabel2.setText("soyad");

        jLabel3.setText("brans");

        jButtonTamam.setText("Tamam");
        jButtonTamam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTamamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel3))
                    .addComponent(isimLbl3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soyadLbl)
                            .addComponent(bransLbl)
                            .addComponent(adLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adTxtFld)
                            .addComponent(soyadTxtFld)
                            .addComponent(bransTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(dbKaydetBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(jButtonTamam)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adLbl)
                    .addComponent(adTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soyadLbl)
                    .addComponent(soyadTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bransLbl)
                    .addComponent(bransTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(isimLbl3)
                .addGap(18, 18, 18)
                .addComponent(dbKaydetBtn)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButtonTamam)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adTxtFldActionPerformed

    private void dbKaydetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbKaydetBtnMouseClicked
        ogretmentKaydet(); 
    }//GEN-LAST:event_dbKaydetBtnMouseClicked

    private void jButtonTamamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTamamMouseClicked
        previousJFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonTamamMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adLbl;
    private javax.swing.JTextField adTxtFld;
    private javax.swing.JLabel bransLbl;
    private javax.swing.JTextField bransTxtFld;
    private javax.swing.JButton dbKaydetBtn;
    private javax.swing.JLabel isimLbl3;
    private javax.swing.JButton jButtonTamam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel soyadLbl;
    private javax.swing.JTextField soyadTxtFld;
    // End of variables declaration//GEN-END:variables

    private void ogretmentKaydet() {
        try {
            DBHelper dbHelper = new DBHelper("otoder");
            ResultSet rs = dbHelper.recordSelect("ogretmen", "*", "", "");
            
            while(rs.next()){
                if(adTxtFld.getText().equals(rs.getString( rs.findColumn("isim"))) &&
                       soyadTxtFld.getText().equals(rs.getString( rs.findColumn("soyisim"))) && 
                        bransTxtFld.getText().equals(rs.getString( rs.findColumn("brans")))){
                    BilgilendirmePaneli bilgiEkran=new BilgilendirmePaneli( this , "isim   soyad   brans\n" +
                           adTxtFld.getText().toString()+soyadTxtFld.getText().toString()+bransTxtFld.getText().toString() );
                   // JPanel bilgiEkran=new JPanel();
                   // bilgiEkran.setSize(200, WIDTH);
                    bilgiEkran.setVisible(true);
                    
                    
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
