/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * Sistem baslatildiginda ilk ekranin olusmasi gosterilmesi ve eventlerin 
 * check edecek class
 */
package otoder;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.DBHelper;

/**
 *
 * @author Cihan
 */
public class SistemGirisPaneli extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGiris
     */
    public SistemGirisPaneli() {
        initComponents();
    }
    
    //giris butonuna basildiginda database baglanir ve 
    //sistem kullanici adi ve sifresini kontrol eder
    //sistemde kayitliysa kullanici id sini dondurur
    public int checkEntry( String name , String password ) throws SQLException{
        DBHelper dbHelper = new DBHelper("otoder");
        ResultSet rs = dbHelper.recordSelect("yonetici", "*", "", "");
        String m_name,m_pass;

        while( rs.next() ){
            m_name = rs.getString( rs.findColumn("isim"));
            m_pass = rs.getString( rs.findColumn("sifre"));
            if( name.equals(name) && m_pass.equals(password)){
                return rs.getInt(rs.findColumn("id"));
            }
        }
        infoJLabel.setText("Kullanici Bulunamadi!");
        return 0; 
    }
    
    void close(){
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGiris = new java.awt.Button();
        sifreLabel = new javax.swing.JLabel();
        kullaniciAdiLabel = new javax.swing.JLabel();
        sifreTextField = new java.awt.TextField();
        kullaniciAdiTextField = new java.awt.TextField();
        infoJLabel = new javax.swing.JLabel();
        exitJButton = new javax.swing.JButton();
        SistemGirisBaslik = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        buttonGiris.setLabel("Giriş Yap");
        buttonGiris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGirisMouseClicked(evt);
            }
        });

        sifreLabel.setText("Şifre");

        kullaniciAdiLabel.setText("Kullanıcı Adı");

        kullaniciAdiTextField.setName("");

        exitJButton.setText("Çıkış");
        exitJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sifreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullaniciAdiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGiris, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(exitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(infoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kullaniciAdiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sifreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(infoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitJButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        SistemGirisBaslik.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OTODER DERSHANE SİSTEMİ");

        javax.swing.GroupLayout SistemGirisBaslikLayout = new javax.swing.GroupLayout(SistemGirisBaslik);
        SistemGirisBaslik.setLayout(SistemGirisBaslikLayout);
        SistemGirisBaslikLayout.setHorizontalGroup(
            SistemGirisBaslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SistemGirisBaslikLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        SistemGirisBaslikLayout.setVerticalGroup(
            SistemGirisBaslikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SistemGirisBaslik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SistemGirisBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGirisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGirisMouseClicked
        int admin_id = 0;
        try {
            String name = kullaniciAdiTextField.getText().toString();
            String password = sifreTextField.getText().toString();
            
            if( name.length() == 0 || password.length() == 0 ){
                infoJLabel.setText("Lutfen bos alanlari giriniz !");
                return;
            }
            admin_id = checkEntry(name, password);
            System.out.println("Entry : " + admin_id );
            
        } catch (SQLException ex) {
            Logger.getLogger(SistemGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if( admin_id > 0 ){
            DershanePaneli dershane = new DershanePaneli( admin_id, this );
            this.setVisible(false);
            dershane.setVisible(true);
        }
        
    }//GEN-LAST:event_buttonGirisMouseClicked

    private void exitJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitJButtonMouseClicked
        close();
    }//GEN-LAST:event_exitJButtonMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SistemGirisBaslik;
    private java.awt.Button buttonGiris;
    private javax.swing.JButton exitJButton;
    private javax.swing.JLabel infoJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kullaniciAdiLabel;
    private java.awt.TextField kullaniciAdiTextField;
    private javax.swing.JLabel sifreLabel;
    private java.awt.TextField sifreTextField;
    // End of variables declaration//GEN-END:variables
}
